# Generated by Django 4.1.5 on 2023-01-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_alter_producttranslation_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
