# Generated by Django 4.1.5 on 2023-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_delete_producttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='hello', max_length=512, verbose_name='tavsif_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='hello', max_length=255, verbose_name='imya'),
            preserve_default=False,
        ),
    ]
